#ifndef PROTOBUF_INCLUDED_command_2eproto
#define PROTOBUF_INCLUDED_command_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_command_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_command_2eproto {
    static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
    static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
    static const ::google::protobuf::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
    static const ::google::protobuf::internal::FieldMetadata field_metadata[];
    static const ::google::protobuf::internal::SerializationTable serialization_table[];
    static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_command_2eproto();
namespace v2ray
{
    namespace core
    {
        namespace app
        {
            namespace stats
            {
                namespace command
                {
                    class Config;
                    class ConfigDefaultTypeInternal;
                    extern ConfigDefaultTypeInternal _Config_default_instance_;
                    class GetStatsRequest;
                    class GetStatsRequestDefaultTypeInternal;
                    extern GetStatsRequestDefaultTypeInternal _GetStatsRequest_default_instance_;
                    class GetStatsResponse;
                    class GetStatsResponseDefaultTypeInternal;
                    extern GetStatsResponseDefaultTypeInternal _GetStatsResponse_default_instance_;
                    class QueryStatsRequest;
                    class QueryStatsRequestDefaultTypeInternal;
                    extern QueryStatsRequestDefaultTypeInternal _QueryStatsRequest_default_instance_;
                    class QueryStatsResponse;
                    class QueryStatsResponseDefaultTypeInternal;
                    extern QueryStatsResponseDefaultTypeInternal _QueryStatsResponse_default_instance_;
                    class Stat;
                    class StatDefaultTypeInternal;
                    extern StatDefaultTypeInternal _Stat_default_instance_;
                    class SysStatsRequest;
                    class SysStatsRequestDefaultTypeInternal;
                    extern SysStatsRequestDefaultTypeInternal _SysStatsRequest_default_instance_;
                    class SysStatsResponse;
                    class SysStatsResponseDefaultTypeInternal;
                    extern SysStatsResponseDefaultTypeInternal _SysStatsResponse_default_instance_;
                }  // namespace command
            }  // namespace stats
        }  // namespace app
    }  // namespace core
}  // namespace v2ray
namespace google
{
    namespace protobuf
    {
        template<> ::v2ray::core::app::stats::command::Config *Arena::CreateMaybeMessage<::v2ray::core::app::stats::command::Config>(Arena *);
        template<> ::v2ray::core::app::stats::command::GetStatsRequest *Arena::CreateMaybeMessage<::v2ray::core::app::stats::command::GetStatsRequest>(Arena *);
        template<> ::v2ray::core::app::stats::command::GetStatsResponse *Arena::CreateMaybeMessage<::v2ray::core::app::stats::command::GetStatsResponse>(Arena *);
        template<> ::v2ray::core::app::stats::command::QueryStatsRequest *Arena::CreateMaybeMessage<::v2ray::core::app::stats::command::QueryStatsRequest>(Arena *);
        template<> ::v2ray::core::app::stats::command::QueryStatsResponse *Arena::CreateMaybeMessage<::v2ray::core::app::stats::command::QueryStatsResponse>(Arena *);
        template<> ::v2ray::core::app::stats::command::Stat *Arena::CreateMaybeMessage<::v2ray::core::app::stats::command::Stat>(Arena *);
        template<> ::v2ray::core::app::stats::command::SysStatsRequest *Arena::CreateMaybeMessage<::v2ray::core::app::stats::command::SysStatsRequest>(Arena *);
        template<> ::v2ray::core::app::stats::command::SysStatsResponse *Arena::CreateMaybeMessage<::v2ray::core::app::stats::command::SysStatsResponse>(Arena *);
    }  // namespace protobuf
}  // namespace google
namespace v2ray
{
    namespace core
    {
        namespace app
        {
            namespace stats
            {
                namespace command
                {

                    // ===================================================================

                    class GetStatsRequest final :
                        public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v2ray.core.app.stats.command.GetStatsRequest) */
                    {
                        public:
                            GetStatsRequest();
                            virtual ~GetStatsRequest();

                            GetStatsRequest(const GetStatsRequest &from);

                            inline GetStatsRequest &operator=(const GetStatsRequest &from)
                            {
                                CopyFrom(from);
                                return *this;
                            }
#if LANG_CXX11
                            GetStatsRequest(GetStatsRequest &&from) noexcept
                                : GetStatsRequest()
                            {
                                *this = ::std::move(from);
                            }

                            inline GetStatsRequest &operator=(GetStatsRequest &&from) noexcept
                            {
                                if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
                                    if (this != &from) InternalSwap(&from);
                                } else {
                                    CopyFrom(from);
                                }

                                return *this;
                            }
#endif
                            static const ::google::protobuf::Descriptor *descriptor()
                            {
                                return default_instance().GetDescriptor();
                            }
                            static const GetStatsRequest &default_instance();

                            static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
                            static inline const GetStatsRequest *internal_default_instance()
                            {
                                return reinterpret_cast<const GetStatsRequest *>(
                                           &_GetStatsRequest_default_instance_);
                            }
                            static constexpr int kIndexInFileMessages =
                                0;

                            void Swap(GetStatsRequest *other);
                            friend void swap(GetStatsRequest &a, GetStatsRequest &b)
                            {
                                a.Swap(&b);
                            }

                            // implements Message ----------------------------------------------

                            inline GetStatsRequest *New() const final
                            {
                                return CreateMaybeMessage<GetStatsRequest>(nullptr);
                            }

                            GetStatsRequest *New(::google::protobuf::Arena *arena) const final
                            {
                                return CreateMaybeMessage<GetStatsRequest>(arena);
                            }
                            void CopyFrom(const ::google::protobuf::Message &from) final;
                            void MergeFrom(const ::google::protobuf::Message &from) final;
                            void CopyFrom(const GetStatsRequest &from);
                            void MergeFrom(const GetStatsRequest &from);
                            PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
                            bool IsInitialized() const final;

                            size_t ByteSizeLong() const final;
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            static const char *_InternalParse(const char *begin, const char *end, void *object, ::google::protobuf::internal::ParseContext *ctx);
                            ::google::protobuf::internal::ParseFunc _ParseFunc() const final
                            {
                                return _InternalParse;
                            }
#else
                            bool MergePartialFromCodedStream(
                                ::google::protobuf::io::CodedInputStream *input) final;
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            void SerializeWithCachedSizes(
                                ::google::protobuf::io::CodedOutputStream *output) const final;
                            ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
                                ::google::protobuf::uint8 *target) const final;
                            int GetCachedSize() const final
                            {
                                return _cached_size_.Get();
                            }

                        private:
                            void SharedCtor();
                            void SharedDtor();
                            void SetCachedSize(int size) const final;
                            void InternalSwap(GetStatsRequest *other);
                        private:
                            inline ::google::protobuf::Arena *GetArenaNoVirtual() const
                            {
                                return nullptr;
                            }
                            inline void *MaybeArenaPtr() const
                            {
                                return nullptr;
                            }
                        public:

                            ::google::protobuf::Metadata GetMetadata() const final;

                            // nested types ----------------------------------------------------

                            // accessors -------------------------------------------------------

                            // string name = 1;
                            void clear_name();
                            static const int kNameFieldNumber = 1;
                            const ::std::string &name() const;
                            void set_name(const ::std::string &value);
#if LANG_CXX11
                            void set_name(::std::string &&value);
#endif
                            void set_name(const char *value);
                            void set_name(const char *value, size_t size);
                            ::std::string *mutable_name();
                            ::std::string *release_name();
                            void set_allocated_name(::std::string *name);

                            // bool reset = 2;
                            void clear_reset();
                            static const int kResetFieldNumber = 2;
                            bool reset() const;
                            void set_reset(bool value);

                            // @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.GetStatsRequest)
                        private:
                            class HasBitSetters;

                            ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                            ::google::protobuf::internal::ArenaStringPtr name_;
                            bool reset_;
                            mutable ::google::protobuf::internal::CachedSize _cached_size_;
                            friend struct ::TableStruct_command_2eproto;
                    };
                    // -------------------------------------------------------------------

                    class Stat final :
                        public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v2ray.core.app.stats.command.Stat) */
                    {
                        public:
                            Stat();
                            virtual ~Stat();

                            Stat(const Stat &from);

                            inline Stat &operator=(const Stat &from)
                            {
                                CopyFrom(from);
                                return *this;
                            }
#if LANG_CXX11
                            Stat(Stat &&from) noexcept
                                : Stat()
                            {
                                *this = ::std::move(from);
                            }

                            inline Stat &operator=(Stat &&from) noexcept
                            {
                                if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
                                    if (this != &from) InternalSwap(&from);
                                } else {
                                    CopyFrom(from);
                                }

                                return *this;
                            }
#endif
                            static const ::google::protobuf::Descriptor *descriptor()
                            {
                                return default_instance().GetDescriptor();
                            }
                            static const Stat &default_instance();

                            static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
                            static inline const Stat *internal_default_instance()
                            {
                                return reinterpret_cast<const Stat *>(
                                           &_Stat_default_instance_);
                            }
                            static constexpr int kIndexInFileMessages =
                                1;

                            void Swap(Stat *other);
                            friend void swap(Stat &a, Stat &b)
                            {
                                a.Swap(&b);
                            }

                            // implements Message ----------------------------------------------

                            inline Stat *New() const final
                            {
                                return CreateMaybeMessage<Stat>(nullptr);
                            }

                            Stat *New(::google::protobuf::Arena *arena) const final
                            {
                                return CreateMaybeMessage<Stat>(arena);
                            }
                            void CopyFrom(const ::google::protobuf::Message &from) final;
                            void MergeFrom(const ::google::protobuf::Message &from) final;
                            void CopyFrom(const Stat &from);
                            void MergeFrom(const Stat &from);
                            PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
                            bool IsInitialized() const final;

                            size_t ByteSizeLong() const final;
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            static const char *_InternalParse(const char *begin, const char *end, void *object, ::google::protobuf::internal::ParseContext *ctx);
                            ::google::protobuf::internal::ParseFunc _ParseFunc() const final
                            {
                                return _InternalParse;
                            }
#else
                            bool MergePartialFromCodedStream(
                                ::google::protobuf::io::CodedInputStream *input) final;
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            void SerializeWithCachedSizes(
                                ::google::protobuf::io::CodedOutputStream *output) const final;
                            ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
                                ::google::protobuf::uint8 *target) const final;
                            int GetCachedSize() const final
                            {
                                return _cached_size_.Get();
                            }

                        private:
                            void SharedCtor();
                            void SharedDtor();
                            void SetCachedSize(int size) const final;
                            void InternalSwap(Stat *other);
                        private:
                            inline ::google::protobuf::Arena *GetArenaNoVirtual() const
                            {
                                return nullptr;
                            }
                            inline void *MaybeArenaPtr() const
                            {
                                return nullptr;
                            }
                        public:

                            ::google::protobuf::Metadata GetMetadata() const final;

                            // nested types ----------------------------------------------------

                            // accessors -------------------------------------------------------

                            // string name = 1;
                            void clear_name();
                            static const int kNameFieldNumber = 1;
                            const ::std::string &name() const;
                            void set_name(const ::std::string &value);
#if LANG_CXX11
                            void set_name(::std::string &&value);
#endif
                            void set_name(const char *value);
                            void set_name(const char *value, size_t size);
                            ::std::string *mutable_name();
                            ::std::string *release_name();
                            void set_allocated_name(::std::string *name);

                            // int64 value = 2;
                            void clear_value();
                            static const int kValueFieldNumber = 2;
                            ::google::protobuf::int64 value() const;
                            void set_value(::google::protobuf::int64 value);

                            // @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.Stat)
                        private:
                            class HasBitSetters;

                            ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                            ::google::protobuf::internal::ArenaStringPtr name_;
                            ::google::protobuf::int64 value_;
                            mutable ::google::protobuf::internal::CachedSize _cached_size_;
                            friend struct ::TableStruct_command_2eproto;
                    };
                    // -------------------------------------------------------------------

                    class GetStatsResponse final :
                        public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v2ray.core.app.stats.command.GetStatsResponse) */
                    {
                        public:
                            GetStatsResponse();
                            virtual ~GetStatsResponse();

                            GetStatsResponse(const GetStatsResponse &from);

                            inline GetStatsResponse &operator=(const GetStatsResponse &from)
                            {
                                CopyFrom(from);
                                return *this;
                            }
#if LANG_CXX11
                            GetStatsResponse(GetStatsResponse &&from) noexcept
                                : GetStatsResponse()
                            {
                                *this = ::std::move(from);
                            }

                            inline GetStatsResponse &operator=(GetStatsResponse &&from) noexcept
                            {
                                if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
                                    if (this != &from) InternalSwap(&from);
                                } else {
                                    CopyFrom(from);
                                }

                                return *this;
                            }
#endif
                            static const ::google::protobuf::Descriptor *descriptor()
                            {
                                return default_instance().GetDescriptor();
                            }
                            static const GetStatsResponse &default_instance();

                            static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
                            static inline const GetStatsResponse *internal_default_instance()
                            {
                                return reinterpret_cast<const GetStatsResponse *>(
                                           &_GetStatsResponse_default_instance_);
                            }
                            static constexpr int kIndexInFileMessages =
                                2;

                            void Swap(GetStatsResponse *other);
                            friend void swap(GetStatsResponse &a, GetStatsResponse &b)
                            {
                                a.Swap(&b);
                            }

                            // implements Message ----------------------------------------------

                            inline GetStatsResponse *New() const final
                            {
                                return CreateMaybeMessage<GetStatsResponse>(nullptr);
                            }

                            GetStatsResponse *New(::google::protobuf::Arena *arena) const final
                            {
                                return CreateMaybeMessage<GetStatsResponse>(arena);
                            }
                            void CopyFrom(const ::google::protobuf::Message &from) final;
                            void MergeFrom(const ::google::protobuf::Message &from) final;
                            void CopyFrom(const GetStatsResponse &from);
                            void MergeFrom(const GetStatsResponse &from);
                            PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
                            bool IsInitialized() const final;

                            size_t ByteSizeLong() const final;
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            static const char *_InternalParse(const char *begin, const char *end, void *object, ::google::protobuf::internal::ParseContext *ctx);
                            ::google::protobuf::internal::ParseFunc _ParseFunc() const final
                            {
                                return _InternalParse;
                            }
#else
                            bool MergePartialFromCodedStream(
                                ::google::protobuf::io::CodedInputStream *input) final;
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            void SerializeWithCachedSizes(
                                ::google::protobuf::io::CodedOutputStream *output) const final;
                            ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
                                ::google::protobuf::uint8 *target) const final;
                            int GetCachedSize() const final
                            {
                                return _cached_size_.Get();
                            }

                        private:
                            void SharedCtor();
                            void SharedDtor();
                            void SetCachedSize(int size) const final;
                            void InternalSwap(GetStatsResponse *other);
                        private:
                            inline ::google::protobuf::Arena *GetArenaNoVirtual() const
                            {
                                return nullptr;
                            }
                            inline void *MaybeArenaPtr() const
                            {
                                return nullptr;
                            }
                        public:

                            ::google::protobuf::Metadata GetMetadata() const final;

                            // nested types ----------------------------------------------------

                            // accessors -------------------------------------------------------

                            // .v2ray.core.app.stats.command.Stat stat = 1;
                            bool has_stat() const;
                            void clear_stat();
                            static const int kStatFieldNumber = 1;
                            const ::v2ray::core::app::stats::command::Stat &stat() const;
                            ::v2ray::core::app::stats::command::Stat *release_stat();
                            ::v2ray::core::app::stats::command::Stat *mutable_stat();
                            void set_allocated_stat(::v2ray::core::app::stats::command::Stat *stat);

                            // @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.GetStatsResponse)
                        private:
                            class HasBitSetters;

                            ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                            ::v2ray::core::app::stats::command::Stat *stat_;
                            mutable ::google::protobuf::internal::CachedSize _cached_size_;
                            friend struct ::TableStruct_command_2eproto;
                    };
                    // -------------------------------------------------------------------

                    class QueryStatsRequest final :
                        public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v2ray.core.app.stats.command.QueryStatsRequest) */
                    {
                        public:
                            QueryStatsRequest();
                            virtual ~QueryStatsRequest();

                            QueryStatsRequest(const QueryStatsRequest &from);

                            inline QueryStatsRequest &operator=(const QueryStatsRequest &from)
                            {
                                CopyFrom(from);
                                return *this;
                            }
#if LANG_CXX11
                            QueryStatsRequest(QueryStatsRequest &&from) noexcept
                                : QueryStatsRequest()
                            {
                                *this = ::std::move(from);
                            }

                            inline QueryStatsRequest &operator=(QueryStatsRequest &&from) noexcept
                            {
                                if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
                                    if (this != &from) InternalSwap(&from);
                                } else {
                                    CopyFrom(from);
                                }

                                return *this;
                            }
#endif
                            static const ::google::protobuf::Descriptor *descriptor()
                            {
                                return default_instance().GetDescriptor();
                            }
                            static const QueryStatsRequest &default_instance();

                            static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
                            static inline const QueryStatsRequest *internal_default_instance()
                            {
                                return reinterpret_cast<const QueryStatsRequest *>(
                                           &_QueryStatsRequest_default_instance_);
                            }
                            static constexpr int kIndexInFileMessages =
                                3;

                            void Swap(QueryStatsRequest *other);
                            friend void swap(QueryStatsRequest &a, QueryStatsRequest &b)
                            {
                                a.Swap(&b);
                            }

                            // implements Message ----------------------------------------------

                            inline QueryStatsRequest *New() const final
                            {
                                return CreateMaybeMessage<QueryStatsRequest>(nullptr);
                            }

                            QueryStatsRequest *New(::google::protobuf::Arena *arena) const final
                            {
                                return CreateMaybeMessage<QueryStatsRequest>(arena);
                            }
                            void CopyFrom(const ::google::protobuf::Message &from) final;
                            void MergeFrom(const ::google::protobuf::Message &from) final;
                            void CopyFrom(const QueryStatsRequest &from);
                            void MergeFrom(const QueryStatsRequest &from);
                            PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
                            bool IsInitialized() const final;

                            size_t ByteSizeLong() const final;
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            static const char *_InternalParse(const char *begin, const char *end, void *object, ::google::protobuf::internal::ParseContext *ctx);
                            ::google::protobuf::internal::ParseFunc _ParseFunc() const final
                            {
                                return _InternalParse;
                            }
#else
                            bool MergePartialFromCodedStream(
                                ::google::protobuf::io::CodedInputStream *input) final;
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            void SerializeWithCachedSizes(
                                ::google::protobuf::io::CodedOutputStream *output) const final;
                            ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
                                ::google::protobuf::uint8 *target) const final;
                            int GetCachedSize() const final
                            {
                                return _cached_size_.Get();
                            }

                        private:
                            void SharedCtor();
                            void SharedDtor();
                            void SetCachedSize(int size) const final;
                            void InternalSwap(QueryStatsRequest *other);
                        private:
                            inline ::google::protobuf::Arena *GetArenaNoVirtual() const
                            {
                                return nullptr;
                            }
                            inline void *MaybeArenaPtr() const
                            {
                                return nullptr;
                            }
                        public:

                            ::google::protobuf::Metadata GetMetadata() const final;

                            // nested types ----------------------------------------------------

                            // accessors -------------------------------------------------------

                            // string pattern = 1;
                            void clear_pattern();
                            static const int kPatternFieldNumber = 1;
                            const ::std::string &pattern() const;
                            void set_pattern(const ::std::string &value);
#if LANG_CXX11
                            void set_pattern(::std::string &&value);
#endif
                            void set_pattern(const char *value);
                            void set_pattern(const char *value, size_t size);
                            ::std::string *mutable_pattern();
                            ::std::string *release_pattern();
                            void set_allocated_pattern(::std::string *pattern);

                            // bool reset = 2;
                            void clear_reset();
                            static const int kResetFieldNumber = 2;
                            bool reset() const;
                            void set_reset(bool value);

                            // @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.QueryStatsRequest)
                        private:
                            class HasBitSetters;

                            ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                            ::google::protobuf::internal::ArenaStringPtr pattern_;
                            bool reset_;
                            mutable ::google::protobuf::internal::CachedSize _cached_size_;
                            friend struct ::TableStruct_command_2eproto;
                    };
                    // -------------------------------------------------------------------

                    class QueryStatsResponse final :
                        public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v2ray.core.app.stats.command.QueryStatsResponse) */
                    {
                        public:
                            QueryStatsResponse();
                            virtual ~QueryStatsResponse();

                            QueryStatsResponse(const QueryStatsResponse &from);

                            inline QueryStatsResponse &operator=(const QueryStatsResponse &from)
                            {
                                CopyFrom(from);
                                return *this;
                            }
#if LANG_CXX11
                            QueryStatsResponse(QueryStatsResponse &&from) noexcept
                                : QueryStatsResponse()
                            {
                                *this = ::std::move(from);
                            }

                            inline QueryStatsResponse &operator=(QueryStatsResponse &&from) noexcept
                            {
                                if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
                                    if (this != &from) InternalSwap(&from);
                                } else {
                                    CopyFrom(from);
                                }

                                return *this;
                            }
#endif
                            static const ::google::protobuf::Descriptor *descriptor()
                            {
                                return default_instance().GetDescriptor();
                            }
                            static const QueryStatsResponse &default_instance();

                            static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
                            static inline const QueryStatsResponse *internal_default_instance()
                            {
                                return reinterpret_cast<const QueryStatsResponse *>(
                                           &_QueryStatsResponse_default_instance_);
                            }
                            static constexpr int kIndexInFileMessages =
                                4;

                            void Swap(QueryStatsResponse *other);
                            friend void swap(QueryStatsResponse &a, QueryStatsResponse &b)
                            {
                                a.Swap(&b);
                            }

                            // implements Message ----------------------------------------------

                            inline QueryStatsResponse *New() const final
                            {
                                return CreateMaybeMessage<QueryStatsResponse>(nullptr);
                            }

                            QueryStatsResponse *New(::google::protobuf::Arena *arena) const final
                            {
                                return CreateMaybeMessage<QueryStatsResponse>(arena);
                            }
                            void CopyFrom(const ::google::protobuf::Message &from) final;
                            void MergeFrom(const ::google::protobuf::Message &from) final;
                            void CopyFrom(const QueryStatsResponse &from);
                            void MergeFrom(const QueryStatsResponse &from);
                            PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
                            bool IsInitialized() const final;

                            size_t ByteSizeLong() const final;
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            static const char *_InternalParse(const char *begin, const char *end, void *object, ::google::protobuf::internal::ParseContext *ctx);
                            ::google::protobuf::internal::ParseFunc _ParseFunc() const final
                            {
                                return _InternalParse;
                            }
#else
                            bool MergePartialFromCodedStream(
                                ::google::protobuf::io::CodedInputStream *input) final;
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            void SerializeWithCachedSizes(
                                ::google::protobuf::io::CodedOutputStream *output) const final;
                            ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
                                ::google::protobuf::uint8 *target) const final;
                            int GetCachedSize() const final
                            {
                                return _cached_size_.Get();
                            }

                        private:
                            void SharedCtor();
                            void SharedDtor();
                            void SetCachedSize(int size) const final;
                            void InternalSwap(QueryStatsResponse *other);
                        private:
                            inline ::google::protobuf::Arena *GetArenaNoVirtual() const
                            {
                                return nullptr;
                            }
                            inline void *MaybeArenaPtr() const
                            {
                                return nullptr;
                            }
                        public:

                            ::google::protobuf::Metadata GetMetadata() const final;

                            // nested types ----------------------------------------------------

                            // accessors -------------------------------------------------------

                            // repeated .v2ray.core.app.stats.command.Stat stat = 1;
                            int stat_size() const;
                            void clear_stat();
                            static const int kStatFieldNumber = 1;
                            ::v2ray::core::app::stats::command::Stat *mutable_stat(int index);
                            ::google::protobuf::RepeatedPtrField< ::v2ray::core::app::stats::command::Stat > *
                            mutable_stat();
                            const ::v2ray::core::app::stats::command::Stat &stat(int index) const;
                            ::v2ray::core::app::stats::command::Stat *add_stat();
                            const ::google::protobuf::RepeatedPtrField< ::v2ray::core::app::stats::command::Stat > &
                            stat() const;

                            // @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.QueryStatsResponse)
                        private:
                            class HasBitSetters;

                            ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                            ::google::protobuf::RepeatedPtrField< ::v2ray::core::app::stats::command::Stat > stat_;
                            mutable ::google::protobuf::internal::CachedSize _cached_size_;
                            friend struct ::TableStruct_command_2eproto;
                    };
                    // -------------------------------------------------------------------

                    class SysStatsRequest final :
                        public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v2ray.core.app.stats.command.SysStatsRequest) */
                    {
                        public:
                            SysStatsRequest();
                            virtual ~SysStatsRequest();

                            SysStatsRequest(const SysStatsRequest &from);

                            inline SysStatsRequest &operator=(const SysStatsRequest &from)
                            {
                                CopyFrom(from);
                                return *this;
                            }
#if LANG_CXX11
                            SysStatsRequest(SysStatsRequest &&from) noexcept
                                : SysStatsRequest()
                            {
                                *this = ::std::move(from);
                            }

                            inline SysStatsRequest &operator=(SysStatsRequest &&from) noexcept
                            {
                                if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
                                    if (this != &from) InternalSwap(&from);
                                } else {
                                    CopyFrom(from);
                                }

                                return *this;
                            }
#endif
                            static const ::google::protobuf::Descriptor *descriptor()
                            {
                                return default_instance().GetDescriptor();
                            }
                            static const SysStatsRequest &default_instance();

                            static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
                            static inline const SysStatsRequest *internal_default_instance()
                            {
                                return reinterpret_cast<const SysStatsRequest *>(
                                           &_SysStatsRequest_default_instance_);
                            }
                            static constexpr int kIndexInFileMessages =
                                5;

                            void Swap(SysStatsRequest *other);
                            friend void swap(SysStatsRequest &a, SysStatsRequest &b)
                            {
                                a.Swap(&b);
                            }

                            // implements Message ----------------------------------------------

                            inline SysStatsRequest *New() const final
                            {
                                return CreateMaybeMessage<SysStatsRequest>(nullptr);
                            }

                            SysStatsRequest *New(::google::protobuf::Arena *arena) const final
                            {
                                return CreateMaybeMessage<SysStatsRequest>(arena);
                            }
                            void CopyFrom(const ::google::protobuf::Message &from) final;
                            void MergeFrom(const ::google::protobuf::Message &from) final;
                            void CopyFrom(const SysStatsRequest &from);
                            void MergeFrom(const SysStatsRequest &from);
                            PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
                            bool IsInitialized() const final;

                            size_t ByteSizeLong() const final;
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            static const char *_InternalParse(const char *begin, const char *end, void *object, ::google::protobuf::internal::ParseContext *ctx);
                            ::google::protobuf::internal::ParseFunc _ParseFunc() const final
                            {
                                return _InternalParse;
                            }
#else
                            bool MergePartialFromCodedStream(
                                ::google::protobuf::io::CodedInputStream *input) final;
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            void SerializeWithCachedSizes(
                                ::google::protobuf::io::CodedOutputStream *output) const final;
                            ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
                                ::google::protobuf::uint8 *target) const final;
                            int GetCachedSize() const final
                            {
                                return _cached_size_.Get();
                            }

                        private:
                            void SharedCtor();
                            void SharedDtor();
                            void SetCachedSize(int size) const final;
                            void InternalSwap(SysStatsRequest *other);
                        private:
                            inline ::google::protobuf::Arena *GetArenaNoVirtual() const
                            {
                                return nullptr;
                            }
                            inline void *MaybeArenaPtr() const
                            {
                                return nullptr;
                            }
                        public:

                            ::google::protobuf::Metadata GetMetadata() const final;

                            // nested types ----------------------------------------------------

                            // accessors -------------------------------------------------------

                            // @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.SysStatsRequest)
                        private:
                            class HasBitSetters;

                            ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                            mutable ::google::protobuf::internal::CachedSize _cached_size_;
                            friend struct ::TableStruct_command_2eproto;
                    };
                    // -------------------------------------------------------------------

                    class SysStatsResponse final :
                        public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v2ray.core.app.stats.command.SysStatsResponse) */
                    {
                        public:
                            SysStatsResponse();
                            virtual ~SysStatsResponse();

                            SysStatsResponse(const SysStatsResponse &from);

                            inline SysStatsResponse &operator=(const SysStatsResponse &from)
                            {
                                CopyFrom(from);
                                return *this;
                            }
#if LANG_CXX11
                            SysStatsResponse(SysStatsResponse &&from) noexcept
                                : SysStatsResponse()
                            {
                                *this = ::std::move(from);
                            }

                            inline SysStatsResponse &operator=(SysStatsResponse &&from) noexcept
                            {
                                if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
                                    if (this != &from) InternalSwap(&from);
                                } else {
                                    CopyFrom(from);
                                }

                                return *this;
                            }
#endif
                            static const ::google::protobuf::Descriptor *descriptor()
                            {
                                return default_instance().GetDescriptor();
                            }
                            static const SysStatsResponse &default_instance();

                            static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
                            static inline const SysStatsResponse *internal_default_instance()
                            {
                                return reinterpret_cast<const SysStatsResponse *>(
                                           &_SysStatsResponse_default_instance_);
                            }
                            static constexpr int kIndexInFileMessages =
                                6;

                            void Swap(SysStatsResponse *other);
                            friend void swap(SysStatsResponse &a, SysStatsResponse &b)
                            {
                                a.Swap(&b);
                            }

                            // implements Message ----------------------------------------------

                            inline SysStatsResponse *New() const final
                            {
                                return CreateMaybeMessage<SysStatsResponse>(nullptr);
                            }

                            SysStatsResponse *New(::google::protobuf::Arena *arena) const final
                            {
                                return CreateMaybeMessage<SysStatsResponse>(arena);
                            }
                            void CopyFrom(const ::google::protobuf::Message &from) final;
                            void MergeFrom(const ::google::protobuf::Message &from) final;
                            void CopyFrom(const SysStatsResponse &from);
                            void MergeFrom(const SysStatsResponse &from);
                            PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
                            bool IsInitialized() const final;

                            size_t ByteSizeLong() const final;
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            static const char *_InternalParse(const char *begin, const char *end, void *object, ::google::protobuf::internal::ParseContext *ctx);
                            ::google::protobuf::internal::ParseFunc _ParseFunc() const final
                            {
                                return _InternalParse;
                            }
#else
                            bool MergePartialFromCodedStream(
                                ::google::protobuf::io::CodedInputStream *input) final;
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            void SerializeWithCachedSizes(
                                ::google::protobuf::io::CodedOutputStream *output) const final;
                            ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
                                ::google::protobuf::uint8 *target) const final;
                            int GetCachedSize() const final
                            {
                                return _cached_size_.Get();
                            }

                        private:
                            void SharedCtor();
                            void SharedDtor();
                            void SetCachedSize(int size) const final;
                            void InternalSwap(SysStatsResponse *other);
                        private:
                            inline ::google::protobuf::Arena *GetArenaNoVirtual() const
                            {
                                return nullptr;
                            }
                            inline void *MaybeArenaPtr() const
                            {
                                return nullptr;
                            }
                        public:

                            ::google::protobuf::Metadata GetMetadata() const final;

                            // nested types ----------------------------------------------------

                            // accessors -------------------------------------------------------

                            // uint32 NumGoroutine = 1;
                            void clear_numgoroutine();
                            static const int kNumGoroutineFieldNumber = 1;
                            ::google::protobuf::uint32 numgoroutine() const;
                            void set_numgoroutine(::google::protobuf::uint32 value);

                            // uint32 NumGC = 2;
                            void clear_numgc();
                            static const int kNumGCFieldNumber = 2;
                            ::google::protobuf::uint32 numgc() const;
                            void set_numgc(::google::protobuf::uint32 value);

                            // uint64 Alloc = 3;
                            void clear_alloc();
                            static const int kAllocFieldNumber = 3;
                            ::google::protobuf::uint64 alloc() const;
                            void set_alloc(::google::protobuf::uint64 value);

                            // uint64 TotalAlloc = 4;
                            void clear_totalalloc();
                            static const int kTotalAllocFieldNumber = 4;
                            ::google::protobuf::uint64 totalalloc() const;
                            void set_totalalloc(::google::protobuf::uint64 value);

                            // uint64 Sys = 5;
                            void clear_sys();
                            static const int kSysFieldNumber = 5;
                            ::google::protobuf::uint64 sys() const;
                            void set_sys(::google::protobuf::uint64 value);

                            // uint64 Mallocs = 6;
                            void clear_mallocs();
                            static const int kMallocsFieldNumber = 6;
                            ::google::protobuf::uint64 mallocs() const;
                            void set_mallocs(::google::protobuf::uint64 value);

                            // uint64 Frees = 7;
                            void clear_frees();
                            static const int kFreesFieldNumber = 7;
                            ::google::protobuf::uint64 frees() const;
                            void set_frees(::google::protobuf::uint64 value);

                            // uint64 LiveObjects = 8;
                            void clear_liveobjects();
                            static const int kLiveObjectsFieldNumber = 8;
                            ::google::protobuf::uint64 liveobjects() const;
                            void set_liveobjects(::google::protobuf::uint64 value);

                            // uint64 PauseTotalNs = 9;
                            void clear_pausetotalns();
                            static const int kPauseTotalNsFieldNumber = 9;
                            ::google::protobuf::uint64 pausetotalns() const;
                            void set_pausetotalns(::google::protobuf::uint64 value);

                            // uint32 Uptime = 10;
                            void clear_uptime();
                            static const int kUptimeFieldNumber = 10;
                            ::google::protobuf::uint32 uptime() const;
                            void set_uptime(::google::protobuf::uint32 value);

                            // @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.SysStatsResponse)
                        private:
                            class HasBitSetters;

                            ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                            ::google::protobuf::uint32 numgoroutine_;
                            ::google::protobuf::uint32 numgc_;
                            ::google::protobuf::uint64 alloc_;
                            ::google::protobuf::uint64 totalalloc_;
                            ::google::protobuf::uint64 sys_;
                            ::google::protobuf::uint64 mallocs_;
                            ::google::protobuf::uint64 frees_;
                            ::google::protobuf::uint64 liveobjects_;
                            ::google::protobuf::uint64 pausetotalns_;
                            ::google::protobuf::uint32 uptime_;
                            mutable ::google::protobuf::internal::CachedSize _cached_size_;
                            friend struct ::TableStruct_command_2eproto;
                    };
                    // -------------------------------------------------------------------

                    class Config final :
                        public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v2ray.core.app.stats.command.Config) */
                    {
                        public:
                            Config();
                            virtual ~Config();

                            Config(const Config &from);

                            inline Config &operator=(const Config &from)
                            {
                                CopyFrom(from);
                                return *this;
                            }
#if LANG_CXX11
                            Config(Config &&from) noexcept
                                : Config()
                            {
                                *this = ::std::move(from);
                            }

                            inline Config &operator=(Config &&from) noexcept
                            {
                                if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
                                    if (this != &from) InternalSwap(&from);
                                } else {
                                    CopyFrom(from);
                                }

                                return *this;
                            }
#endif
                            static const ::google::protobuf::Descriptor *descriptor()
                            {
                                return default_instance().GetDescriptor();
                            }
                            static const Config &default_instance();

                            static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
                            static inline const Config *internal_default_instance()
                            {
                                return reinterpret_cast<const Config *>(
                                           &_Config_default_instance_);
                            }
                            static constexpr int kIndexInFileMessages =
                                7;

                            void Swap(Config *other);
                            friend void swap(Config &a, Config &b)
                            {
                                a.Swap(&b);
                            }

                            // implements Message ----------------------------------------------

                            inline Config *New() const final
                            {
                                return CreateMaybeMessage<Config>(nullptr);
                            }

                            Config *New(::google::protobuf::Arena *arena) const final
                            {
                                return CreateMaybeMessage<Config>(arena);
                            }
                            void CopyFrom(const ::google::protobuf::Message &from) final;
                            void MergeFrom(const ::google::protobuf::Message &from) final;
                            void CopyFrom(const Config &from);
                            void MergeFrom(const Config &from);
                            PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
                            bool IsInitialized() const final;

                            size_t ByteSizeLong() const final;
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            static const char *_InternalParse(const char *begin, const char *end, void *object, ::google::protobuf::internal::ParseContext *ctx);
                            ::google::protobuf::internal::ParseFunc _ParseFunc() const final
                            {
                                return _InternalParse;
                            }
#else
                            bool MergePartialFromCodedStream(
                                ::google::protobuf::io::CodedInputStream *input) final;
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
                            void SerializeWithCachedSizes(
                                ::google::protobuf::io::CodedOutputStream *output) const final;
                            ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
                                ::google::protobuf::uint8 *target) const final;
                            int GetCachedSize() const final
                            {
                                return _cached_size_.Get();
                            }

                        private:
                            void SharedCtor();
                            void SharedDtor();
                            void SetCachedSize(int size) const final;
                            void InternalSwap(Config *other);
                        private:
                            inline ::google::protobuf::Arena *GetArenaNoVirtual() const
                            {
                                return nullptr;
                            }
                            inline void *MaybeArenaPtr() const
                            {
                                return nullptr;
                            }
                        public:

                            ::google::protobuf::Metadata GetMetadata() const final;

                            // nested types ----------------------------------------------------

                            // accessors -------------------------------------------------------

                            // @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.Config)
                        private:
                            class HasBitSetters;

                            ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                            mutable ::google::protobuf::internal::CachedSize _cached_size_;
                            friend struct ::TableStruct_command_2eproto;
                    };
                    // ===================================================================


                    // ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
                    // GetStatsRequest

                    // string name = 1;
                    inline void GetStatsRequest::clear_name()
                    {
                        name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline const ::std::string &GetStatsRequest::name() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.GetStatsRequest.name)
                        return name_.GetNoArena();
                    }
                    inline void GetStatsRequest::set_name(const ::std::string &value)
                    {
                        name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.GetStatsRequest.name)
                    }
#if LANG_CXX11
                    inline void GetStatsRequest::set_name(::std::string &&value)
                    {
                        name_.SetNoArena(
                            &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
                        // @@protoc_insertion_point(field_set_rvalue:v2ray.core.app.stats.command.GetStatsRequest.name)
                    }
#endif
                    inline void GetStatsRequest::set_name(const char *value)
                    {
                        GOOGLE_DCHECK(value != nullptr);
                        name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
                        // @@protoc_insertion_point(field_set_char:v2ray.core.app.stats.command.GetStatsRequest.name)
                    }
                    inline void GetStatsRequest::set_name(const char *value, size_t size)
                    {
                        name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                                         ::std::string(reinterpret_cast<const char *>(value), size));
                        // @@protoc_insertion_point(field_set_pointer:v2ray.core.app.stats.command.GetStatsRequest.name)
                    }
                    inline ::std::string *GetStatsRequest::mutable_name()
                    {
                        // @@protoc_insertion_point(field_mutable:v2ray.core.app.stats.command.GetStatsRequest.name)
                        return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline ::std::string *GetStatsRequest::release_name()
                    {
                        // @@protoc_insertion_point(field_release:v2ray.core.app.stats.command.GetStatsRequest.name)
                        return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline void GetStatsRequest::set_allocated_name(::std::string *name)
                    {
                        if (name != nullptr) {
                        } else {
                        }

                        name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
                        // @@protoc_insertion_point(field_set_allocated:v2ray.core.app.stats.command.GetStatsRequest.name)
                    }

                    // bool reset = 2;
                    inline void GetStatsRequest::clear_reset()
                    {
                        reset_ = false;
                    }
                    inline bool GetStatsRequest::reset() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.GetStatsRequest.reset)
                        return reset_;
                    }
                    inline void GetStatsRequest::set_reset(bool value)
                    {
                        reset_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.GetStatsRequest.reset)
                    }

                    // -------------------------------------------------------------------

                    // Stat

                    // string name = 1;
                    inline void Stat::clear_name()
                    {
                        name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline const ::std::string &Stat::name() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.Stat.name)
                        return name_.GetNoArena();
                    }
                    inline void Stat::set_name(const ::std::string &value)
                    {
                        name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.Stat.name)
                    }
#if LANG_CXX11
                    inline void Stat::set_name(::std::string &&value)
                    {
                        name_.SetNoArena(
                            &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
                        // @@protoc_insertion_point(field_set_rvalue:v2ray.core.app.stats.command.Stat.name)
                    }
#endif
                    inline void Stat::set_name(const char *value)
                    {
                        GOOGLE_DCHECK(value != nullptr);
                        name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
                        // @@protoc_insertion_point(field_set_char:v2ray.core.app.stats.command.Stat.name)
                    }
                    inline void Stat::set_name(const char *value, size_t size)
                    {
                        name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                                         ::std::string(reinterpret_cast<const char *>(value), size));
                        // @@protoc_insertion_point(field_set_pointer:v2ray.core.app.stats.command.Stat.name)
                    }
                    inline ::std::string *Stat::mutable_name()
                    {
                        // @@protoc_insertion_point(field_mutable:v2ray.core.app.stats.command.Stat.name)
                        return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline ::std::string *Stat::release_name()
                    {
                        // @@protoc_insertion_point(field_release:v2ray.core.app.stats.command.Stat.name)
                        return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline void Stat::set_allocated_name(::std::string *name)
                    {
                        if (name != nullptr) {
                        } else {
                        }

                        name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
                        // @@protoc_insertion_point(field_set_allocated:v2ray.core.app.stats.command.Stat.name)
                    }

                    // int64 value = 2;
                    inline void Stat::clear_value()
                    {
                        value_ = PROTOBUF_LONGLONG(0);
                    }
                    inline ::google::protobuf::int64 Stat::value() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.Stat.value)
                        return value_;
                    }
                    inline void Stat::set_value(::google::protobuf::int64 value)
                    {
                        value_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.Stat.value)
                    }

                    // -------------------------------------------------------------------

                    // GetStatsResponse

                    // .v2ray.core.app.stats.command.Stat stat = 1;
                    inline bool GetStatsResponse::has_stat() const
                    {
                        return this != internal_default_instance() && stat_ != nullptr;
                    }
                    inline void GetStatsResponse::clear_stat()
                    {
                        if (GetArenaNoVirtual() == nullptr && stat_ != nullptr) {
                            delete stat_;
                        }

                        stat_ = nullptr;
                    }
                    inline const ::v2ray::core::app::stats::command::Stat &GetStatsResponse::stat() const
                    {
                        const ::v2ray::core::app::stats::command::Stat *p = stat_;
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.GetStatsResponse.stat)
                        return p != nullptr ? *p : *reinterpret_cast<const ::v2ray::core::app::stats::command::Stat *>(
                                   &::v2ray::core::app::stats::command::_Stat_default_instance_);
                    }
                    inline ::v2ray::core::app::stats::command::Stat *GetStatsResponse::release_stat()
                    {
                        // @@protoc_insertion_point(field_release:v2ray.core.app.stats.command.GetStatsResponse.stat)
                        ::v2ray::core::app::stats::command::Stat *temp = stat_;
                        stat_ = nullptr;
                        return temp;
                    }
                    inline ::v2ray::core::app::stats::command::Stat *GetStatsResponse::mutable_stat()
                    {
                        if (stat_ == nullptr) {
                            auto *p = CreateMaybeMessage<::v2ray::core::app::stats::command::Stat>(GetArenaNoVirtual());
                            stat_ = p;
                        }

                        // @@protoc_insertion_point(field_mutable:v2ray.core.app.stats.command.GetStatsResponse.stat)
                        return stat_;
                    }
                    inline void GetStatsResponse::set_allocated_stat(::v2ray::core::app::stats::command::Stat *stat)
                    {
                        ::google::protobuf::Arena *message_arena = GetArenaNoVirtual();

                        if (message_arena == nullptr) {
                            delete stat_;
                        }

                        if (stat) {
                            ::google::protobuf::Arena *submessage_arena = nullptr;

                            if (message_arena != submessage_arena) {
                                stat = ::google::protobuf::internal::GetOwnedMessage(
                                           message_arena, stat, submessage_arena);
                            }
                        } else {
                        }

                        stat_ = stat;
                        // @@protoc_insertion_point(field_set_allocated:v2ray.core.app.stats.command.GetStatsResponse.stat)
                    }

                    // -------------------------------------------------------------------

                    // QueryStatsRequest

                    // string pattern = 1;
                    inline void QueryStatsRequest::clear_pattern()
                    {
                        pattern_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline const ::std::string &QueryStatsRequest::pattern() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.QueryStatsRequest.pattern)
                        return pattern_.GetNoArena();
                    }
                    inline void QueryStatsRequest::set_pattern(const ::std::string &value)
                    {
                        pattern_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.QueryStatsRequest.pattern)
                    }
#if LANG_CXX11
                    inline void QueryStatsRequest::set_pattern(::std::string &&value)
                    {
                        pattern_.SetNoArena(
                            &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
                        // @@protoc_insertion_point(field_set_rvalue:v2ray.core.app.stats.command.QueryStatsRequest.pattern)
                    }
#endif
                    inline void QueryStatsRequest::set_pattern(const char *value)
                    {
                        GOOGLE_DCHECK(value != nullptr);
                        pattern_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
                        // @@protoc_insertion_point(field_set_char:v2ray.core.app.stats.command.QueryStatsRequest.pattern)
                    }
                    inline void QueryStatsRequest::set_pattern(const char *value, size_t size)
                    {
                        pattern_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
                                            ::std::string(reinterpret_cast<const char *>(value), size));
                        // @@protoc_insertion_point(field_set_pointer:v2ray.core.app.stats.command.QueryStatsRequest.pattern)
                    }
                    inline ::std::string *QueryStatsRequest::mutable_pattern()
                    {
                        // @@protoc_insertion_point(field_mutable:v2ray.core.app.stats.command.QueryStatsRequest.pattern)
                        return pattern_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline ::std::string *QueryStatsRequest::release_pattern()
                    {
                        // @@protoc_insertion_point(field_release:v2ray.core.app.stats.command.QueryStatsRequest.pattern)
                        return pattern_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                    }
                    inline void QueryStatsRequest::set_allocated_pattern(::std::string *pattern)
                    {
                        if (pattern != nullptr) {
                        } else {
                        }

                        pattern_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pattern);
                        // @@protoc_insertion_point(field_set_allocated:v2ray.core.app.stats.command.QueryStatsRequest.pattern)
                    }

                    // bool reset = 2;
                    inline void QueryStatsRequest::clear_reset()
                    {
                        reset_ = false;
                    }
                    inline bool QueryStatsRequest::reset() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.QueryStatsRequest.reset)
                        return reset_;
                    }
                    inline void QueryStatsRequest::set_reset(bool value)
                    {
                        reset_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.QueryStatsRequest.reset)
                    }

                    // -------------------------------------------------------------------

                    // QueryStatsResponse

                    // repeated .v2ray.core.app.stats.command.Stat stat = 1;
                    inline int QueryStatsResponse::stat_size() const
                    {
                        return stat_.size();
                    }
                    inline void QueryStatsResponse::clear_stat()
                    {
                        stat_.Clear();
                    }
                    inline ::v2ray::core::app::stats::command::Stat *QueryStatsResponse::mutable_stat(int index)
                    {
                        // @@protoc_insertion_point(field_mutable:v2ray.core.app.stats.command.QueryStatsResponse.stat)
                        return stat_.Mutable(index);
                    }
                    inline ::google::protobuf::RepeatedPtrField< ::v2ray::core::app::stats::command::Stat > *
                    QueryStatsResponse::mutable_stat()
                    {
                        // @@protoc_insertion_point(field_mutable_list:v2ray.core.app.stats.command.QueryStatsResponse.stat)
                        return &stat_;
                    }
                    inline const ::v2ray::core::app::stats::command::Stat &QueryStatsResponse::stat(int index) const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.QueryStatsResponse.stat)
                        return stat_.Get(index);
                    }
                    inline ::v2ray::core::app::stats::command::Stat *QueryStatsResponse::add_stat()
                    {
                        // @@protoc_insertion_point(field_add:v2ray.core.app.stats.command.QueryStatsResponse.stat)
                        return stat_.Add();
                    }
                    inline const ::google::protobuf::RepeatedPtrField< ::v2ray::core::app::stats::command::Stat > &
                    QueryStatsResponse::stat() const
                    {
                        // @@protoc_insertion_point(field_list:v2ray.core.app.stats.command.QueryStatsResponse.stat)
                        return stat_;
                    }

                    // -------------------------------------------------------------------

                    // SysStatsRequest

                    // -------------------------------------------------------------------

                    // SysStatsResponse

                    // uint32 NumGoroutine = 1;
                    inline void SysStatsResponse::clear_numgoroutine()
                    {
                        numgoroutine_ = 0u;
                    }
                    inline ::google::protobuf::uint32 SysStatsResponse::numgoroutine() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.NumGoroutine)
                        return numgoroutine_;
                    }
                    inline void SysStatsResponse::set_numgoroutine(::google::protobuf::uint32 value)
                    {
                        numgoroutine_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.NumGoroutine)
                    }

                    // uint32 NumGC = 2;
                    inline void SysStatsResponse::clear_numgc()
                    {
                        numgc_ = 0u;
                    }
                    inline ::google::protobuf::uint32 SysStatsResponse::numgc() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.NumGC)
                        return numgc_;
                    }
                    inline void SysStatsResponse::set_numgc(::google::protobuf::uint32 value)
                    {
                        numgc_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.NumGC)
                    }

                    // uint64 Alloc = 3;
                    inline void SysStatsResponse::clear_alloc()
                    {
                        alloc_ = PROTOBUF_ULONGLONG(0);
                    }
                    inline ::google::protobuf::uint64 SysStatsResponse::alloc() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.Alloc)
                        return alloc_;
                    }
                    inline void SysStatsResponse::set_alloc(::google::protobuf::uint64 value)
                    {
                        alloc_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.Alloc)
                    }

                    // uint64 TotalAlloc = 4;
                    inline void SysStatsResponse::clear_totalalloc()
                    {
                        totalalloc_ = PROTOBUF_ULONGLONG(0);
                    }
                    inline ::google::protobuf::uint64 SysStatsResponse::totalalloc() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.TotalAlloc)
                        return totalalloc_;
                    }
                    inline void SysStatsResponse::set_totalalloc(::google::protobuf::uint64 value)
                    {
                        totalalloc_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.TotalAlloc)
                    }

                    // uint64 Sys = 5;
                    inline void SysStatsResponse::clear_sys()
                    {
                        sys_ = PROTOBUF_ULONGLONG(0);
                    }
                    inline ::google::protobuf::uint64 SysStatsResponse::sys() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.Sys)
                        return sys_;
                    }
                    inline void SysStatsResponse::set_sys(::google::protobuf::uint64 value)
                    {
                        sys_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.Sys)
                    }

                    // uint64 Mallocs = 6;
                    inline void SysStatsResponse::clear_mallocs()
                    {
                        mallocs_ = PROTOBUF_ULONGLONG(0);
                    }
                    inline ::google::protobuf::uint64 SysStatsResponse::mallocs() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.Mallocs)
                        return mallocs_;
                    }
                    inline void SysStatsResponse::set_mallocs(::google::protobuf::uint64 value)
                    {
                        mallocs_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.Mallocs)
                    }

                    // uint64 Frees = 7;
                    inline void SysStatsResponse::clear_frees()
                    {
                        frees_ = PROTOBUF_ULONGLONG(0);
                    }
                    inline ::google::protobuf::uint64 SysStatsResponse::frees() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.Frees)
                        return frees_;
                    }
                    inline void SysStatsResponse::set_frees(::google::protobuf::uint64 value)
                    {
                        frees_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.Frees)
                    }

                    // uint64 LiveObjects = 8;
                    inline void SysStatsResponse::clear_liveobjects()
                    {
                        liveobjects_ = PROTOBUF_ULONGLONG(0);
                    }
                    inline ::google::protobuf::uint64 SysStatsResponse::liveobjects() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.LiveObjects)
                        return liveobjects_;
                    }
                    inline void SysStatsResponse::set_liveobjects(::google::protobuf::uint64 value)
                    {
                        liveobjects_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.LiveObjects)
                    }

                    // uint64 PauseTotalNs = 9;
                    inline void SysStatsResponse::clear_pausetotalns()
                    {
                        pausetotalns_ = PROTOBUF_ULONGLONG(0);
                    }
                    inline ::google::protobuf::uint64 SysStatsResponse::pausetotalns() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.PauseTotalNs)
                        return pausetotalns_;
                    }
                    inline void SysStatsResponse::set_pausetotalns(::google::protobuf::uint64 value)
                    {
                        pausetotalns_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.PauseTotalNs)
                    }

                    // uint32 Uptime = 10;
                    inline void SysStatsResponse::clear_uptime()
                    {
                        uptime_ = 0u;
                    }
                    inline ::google::protobuf::uint32 SysStatsResponse::uptime() const
                    {
                        // @@protoc_insertion_point(field_get:v2ray.core.app.stats.command.SysStatsResponse.Uptime)
                        return uptime_;
                    }
                    inline void SysStatsResponse::set_uptime(::google::protobuf::uint32 value)
                    {
                        uptime_ = value;
                        // @@protoc_insertion_point(field_set:v2ray.core.app.stats.command.SysStatsResponse.Uptime)
                    }

                    // -------------------------------------------------------------------

                    // Config

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__
                    // -------------------------------------------------------------------

                    // -------------------------------------------------------------------

                    // -------------------------------------------------------------------

                    // -------------------------------------------------------------------

                    // -------------------------------------------------------------------

                    // -------------------------------------------------------------------

                    // -------------------------------------------------------------------


                    // @@protoc_insertion_point(namespace_scope)

                }  // namespace command
            }  // namespace stats
        }  // namespace app
    }  // namespace core
}  // namespace v2ray

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_command_2eproto
