/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "api.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(v2ray_core_app_stats_command_GetStatsRequest, v2ray_core_app_stats_command_GetStatsRequest, AUTO)


PB_BIND(v2ray_core_app_stats_command_Stat, v2ray_core_app_stats_command_Stat, AUTO)


PB_BIND(v2ray_core_app_stats_command_GetStatsResponse, v2ray_core_app_stats_command_GetStatsResponse, AUTO)



