/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_V2RAY_CORE_APP_STATS_COMMAND_API_PB_H_INCLUDED
#define PB_V2RAY_CORE_APP_STATS_COMMAND_API_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _v2ray_core_app_stats_command_GetStatsRequest { 
    /* Name of the stat counter. */
    pb_callback_t name; 
    /* Whether or not to reset the counter to fetching its value. */
    bool reset; 
} v2ray_core_app_stats_command_GetStatsRequest;

typedef struct _v2ray_core_app_stats_command_Stat { 
    pb_callback_t name; 
    int64_t value; 
} v2ray_core_app_stats_command_Stat;

typedef struct _v2ray_core_app_stats_command_GetStatsResponse { 
    bool has_stat;
    v2ray_core_app_stats_command_Stat stat; 
} v2ray_core_app_stats_command_GetStatsResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define v2ray_core_app_stats_command_GetStatsRequest_init_default {{{NULL}, NULL}, 0}
#define v2ray_core_app_stats_command_Stat_init_default {{{NULL}, NULL}, 0}
#define v2ray_core_app_stats_command_GetStatsResponse_init_default {false, v2ray_core_app_stats_command_Stat_init_default}
#define v2ray_core_app_stats_command_GetStatsRequest_init_zero {{{NULL}, NULL}, 0}
#define v2ray_core_app_stats_command_Stat_init_zero {{{NULL}, NULL}, 0}
#define v2ray_core_app_stats_command_GetStatsResponse_init_zero {false, v2ray_core_app_stats_command_Stat_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define v2ray_core_app_stats_command_GetStatsRequest_name_tag 1
#define v2ray_core_app_stats_command_GetStatsRequest_reset_tag 2
#define v2ray_core_app_stats_command_Stat_name_tag 1
#define v2ray_core_app_stats_command_Stat_value_tag 2
#define v2ray_core_app_stats_command_GetStatsResponse_stat_tag 1

/* Struct field encoding specification for nanopb */
#define v2ray_core_app_stats_command_GetStatsRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, BOOL,     reset,             2)
#define v2ray_core_app_stats_command_GetStatsRequest_CALLBACK pb_default_field_callback
#define v2ray_core_app_stats_command_GetStatsRequest_DEFAULT NULL

#define v2ray_core_app_stats_command_Stat_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, INT64,    value,             2)
#define v2ray_core_app_stats_command_Stat_CALLBACK pb_default_field_callback
#define v2ray_core_app_stats_command_Stat_DEFAULT NULL

#define v2ray_core_app_stats_command_GetStatsResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stat,              1)
#define v2ray_core_app_stats_command_GetStatsResponse_CALLBACK NULL
#define v2ray_core_app_stats_command_GetStatsResponse_DEFAULT NULL
#define v2ray_core_app_stats_command_GetStatsResponse_stat_MSGTYPE v2ray_core_app_stats_command_Stat

extern const pb_msgdesc_t v2ray_core_app_stats_command_GetStatsRequest_msg;
extern const pb_msgdesc_t v2ray_core_app_stats_command_Stat_msg;
extern const pb_msgdesc_t v2ray_core_app_stats_command_GetStatsResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define v2ray_core_app_stats_command_GetStatsRequest_fields &v2ray_core_app_stats_command_GetStatsRequest_msg
#define v2ray_core_app_stats_command_Stat_fields &v2ray_core_app_stats_command_Stat_msg
#define v2ray_core_app_stats_command_GetStatsResponse_fields &v2ray_core_app_stats_command_GetStatsResponse_msg

/* Maximum encoded size of messages (where known) */
/* v2ray_core_app_stats_command_GetStatsRequest_size depends on runtime parameters */
/* v2ray_core_app_stats_command_Stat_size depends on runtime parameters */
/* v2ray_core_app_stats_command_GetStatsResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
