# Starter pipeline

trigger:
  branches:
    include:
      - master
      - dev
  tags:
    include:
      - v*

pool:
  vmImage: "macOS-10.14"

steps:
  - checkout: self
    submodules: recursive
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
  - script: |
      pip3 install aqtinstall
      aqt install --outputdir $AGENT_BUILDDIRECTORY/qt 5.15.1 mac desktop
      brew install protobuf grpc ninja pkg-config tree
      npm install -g appdmg
    displayName: Prepare dependencies
  - script: |
      PATH=$AGENT_BUILDDIRECTORY/qt/5.15.1/clang_64/bin:$PATH
      mkdir build
      cd build
      cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12
      cmake --build .
      sudo cmake --install .
      appdmg ../assets/package_dmg.json ../qv2ray-legacy.dmg
    displayName: Build Qv2ray
    env:
      Qt5_DIR: $(Agent.BuildDirectory)/qt/5.15.1/clang_64/lib/cmake/Qt5
      PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "qv2ray-legacy.dmg"
      ArtifactName: "qv2ray-legacy.dmg"
      publishLocation: "Container"
  - task: GitHubRelease@0
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    inputs:
      gitHubConnection: "GitHub - DuckSoft"
      assets: "qv2ray-legacy.dmg"
      action: edit
      tag: "$(Build.SourceBranchName)"
      isPreRelease: true
      addChangeLog: false
