/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "v2ray_geosite.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(v2ray_core_app_router_DomainObject, v2ray_core_app_router_DomainObject, AUTO)


PB_BIND(v2ray_core_app_router_DomainObject_Attribute, v2ray_core_app_router_DomainObject_Attribute, AUTO)


PB_BIND(v2ray_core_app_router_CIDR, v2ray_core_app_router_CIDR, AUTO)


PB_BIND(v2ray_core_app_router_GeoIP, v2ray_core_app_router_GeoIP, AUTO)


PB_BIND(v2ray_core_app_router_GeoIPList, v2ray_core_app_router_GeoIPList, AUTO)


PB_BIND(v2ray_core_app_router_GeoSite, v2ray_core_app_router_GeoSite, AUTO)


PB_BIND(v2ray_core_app_router_GeoSiteList, v2ray_core_app_router_GeoSiteList, AUTO)




