name: qv2ray
base: core18
adopt-info: qv2ray

grade: devel
confinement: strict

apps:
  qv2ray:
      command: usr/bin/qv2ray
      plugs:
      - home
      - x11
      - opengl
      - network
      - network-bind
      - unity7
      - pulseaudio
      - desktop
      - desktop-legacy
      common-id: com.github.Qv2ray
      desktop: "usr/share/applications/qv2ray.desktop"

parts:
  qv2ray:
    plugin: qmake
    source-type: git
    source: .
    parse-info: [usr/share/metainfo/qv2ray.metainfo.xml]
    build-packages:
      - build-essential
      - software-properties-common
      - libgrpc++-dev
      - libprotobuf-dev
      - protobuf-compiler-grpc
    stage-packages:
      - libgrpc++1
      - libprotobuf17
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5widgets5
    options:
      - PREFIX=/usr
      - CONFIG+=with_metainfo
    override-pull: |
      snapcraftctl pull

      sudo add-apt-repository ppa:ymshenyu/qt
      sudo add-apt-repository ppa:ymshenyu/grpc
      sudo apt-get update

      build_number=$(cat Build.Counter)
      tag=$(git describe --abbrev=0 --tags)
      version=$version.$(cat Build.Counter)

      snapcraftctl set-version "$version"
