name: qv2ray
base: core18
adopt-info: qv2ray
icon: assets/icons/qv2ray.png

grade: stable
confinement: strict

plugs:
  kde-frameworks-5-plug:
      content: kde-frameworks-5-core18-all
      interface: content
      default-provider: kde-frameworks-5-qt-5-14-core18
      target: kf5

apps:
  qv2ray:
      command: kf5-launch qv2ray
      plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - wayland
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - desktop
        - desktop-legacy
        - gsettings
        - network-control
        - network-manager
        - system-observe
      common-id: com.github.Qv2ray
      desktop: "usr/share/applications/qv2ray.desktop"

parts:
  qv2ray:
    plugin: x-qmake
    source-type: git
    source: .
    parse-info: [usr/share/metainfo/qv2ray.metainfo.xml]
    build-packages:
      - build-essential
      - libgrpc++-dev
      - libprotobuf-dev
      - protobuf-compiler-grpc
    build-snaps:
      - kde-frameworks-5-qt-5-14-core18
      - kde-frameworks-5-qt-5-14-core18-sdk
    stage-packages:
      - libgcc1
      - libstdc++6
      - libssl1.1
      - libgrpc++1
      - libprotobuf17
      - libglib2.0-bin
    options:
      - PREFIX=/usr
      - CONFIG+=with_metainfo
      - CONFIG+=use_grpc
    override-pull: |
      snapcraftctl pull
      build_number=$(cat makespec/BUILDVERSION)
      tag=$(git describe --abbrev=0 --tags)
      version=$tag.$build_number
      snapcraftctl set-version "$version"
      sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/256x256/apps/qv2ray.png|g' assets/qv2ray.desktop
    override-build: |
      sudo add-apt-repository -y ppa:ymshenyu/qv2ray-deps
      sudo apt dist-upgrade -y
      snapcraftctl build
    after:
      - kde-frameworks-5-env

  kde-frameworks-5-env:
      plugin: dump
      source: https://github.com/apachelogger/kf5-snap-env.git