name: qv2ray
base: core18
adopt-info: qv2ray

grade: devel
confinement: strict

apps:
  qv2ray:
      command: usr/bin/qv2ray
      plugs:
      - home
      - x11
      - opengl
      - network
      - network-bind
      - unity7
      - pulseaudio
      - desktop
      - desktop-legacy
      common-id: com.github.Qv2ray
      desktop: "usr/share/applications/qv2ray.desktop"

parts:
  qv2ray:
    plugin: qmake
    source-type: git
    source: .
    parse-info: [usr/share/metainfo/qv2ray.metainfo.xml]
    build-packages:
      - build-essential
    stage-packages:
      - libgrpc++1
      - libprotobuf17
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5widgets5
    options:
      - PREFIX=/usr
      - CONFIG+=with_metainfo
      - CONFIG+=use_grpc
    override-pull: |
      snapcraftctl pull
      build_number=$(cat Build.Counter)
      tag=$(git describe --abbrev=0 --tags)
      version=$version.$(cat Build.Counter)
      snapcraftctl set-version "$version"
    after:
      - mytools
  
  mytools:
    plugin: nil
    override-pull: |
      echo "deb http://ppa.launchpad.net/ymshenyu/qt5/ubuntu bionic main" >> /etc/apt/sources.list.d/tools.list
      echo "deb http://ppa.launchpad.net/ymshenyu/grpc/ubuntu bionic main" >> /etc/apt/sources.list.d/tools.list
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 281f24e574404629aa3bda1a4f10c386c55cdb04
      sudo apt-get update
      snapcraftctl pull
    override-build: |
      snapcraftctl build
      sudo apt install -y qttools5-dev-tools qt5-default libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc
      sudo apt upgrade -y