name: Build Pre-Release Qv2ray

on:
  release:
    types: [prereleased]

jobs:
  Windows:
    name: Release for Windows x64
    runs-on: [windows-latest]
    steps:
      - name: Checking out Qv2ray sources
        uses: actions/checkout@master
      - name: Restoring submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing Qt
        uses: lhy0403/install-qt-action@v2
        with:
          arch: win64_mingw73
          modules: qtcharts
# --------------------------------------------------------
      - name: Extracting gRPC and protobuf libs and headers
        run: tools\grpc_gen.bat
# --------------------------------------------------------
#      - name: Download libqvb static library.
#        run: curl -o .\libs\libqvb-win64.a -L https://github.com/Qv2ray/QvRPCBridge/releases/download/v1.0/libqvb-win64.a
# --------------------------------------------------------
      - name: Building Qv2ray
        shell: cmd
        run: |
          mkdir build
          cd build
          qmake .. CONFIG+=no_increase_build_number
          mingw32-make -j2
      - name: Copying DLLs to build output folders
        shell: cmd
        run: .github\workflows\copy_DLLs.bat
      - name: Make release zipball
        shell: cmd
        run: |
          cd build
          cd release
          del *.cpp *.h *.o *.qrc *.qm
          windeployqt ./qv2ray.exe --compiler-runtime
      - name: Create 7z Release
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: ./build/release/
          pathTarget: ./release.7z
      - name: Uploading artifact
        uses: actions/upload-artifact@master
        with:
          name: Qv2ray.Win64.zip
          path: build/Qv2ray.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Qv2ray.zip
          asset_name: Qv2ray-${{ github.ref }}-win64.zip
          tag: ${{ github.ref }}
          overwrite: true

# =========================================================================================

  macOS:
    name: Release for macOS
    runs-on: macos-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@master
      - name: Restoring submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing Qt
        uses: lhy0403/install-qt-action@v2
        with:
          modules: qtcharts
# --------------------------------------------------------
#      - name: Extracting gRPC and protobuf libs and headers
#        run: tools/deps_macOS.sh
# --------------------------------------------------------
      - name: Download libqvb static library.
        run: curl -o .\libs\libqvb-darwin.a -L https://github.com/Qv2ray/QvRPCBridge/releases/download/v1.0/libqvb-darwin.a
# --------------------------------------------------------
      - name: Building Qv2ray
        run: |
          mkdir build
          cd build
          qmake .. CONFIG+=no_increase_build_number CONFIG+=with_new_backend
          make -j2
      - name: Making release tarball
        run: |
          cd build
          cd qv2ray.app
          macdeployqt ./
          cd ..
          tar czf Qv2ray.app.tar.gz qv2ray.app
      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: Qv2ray.macOS.app.zip
          path: build/Qv2ray.app.tar.gz
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Qv2ray.app.tar.gz
          asset_name: Qv2ray-${{ github.ref }}-macOS.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
# ===================================================================================
          
  Linux:
    name: Release for linux
    runs-on: ubuntu-16.04
    steps:
      - name: Checking out sources
        uses: actions/checkout@master
      - name: Restoring submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing Qt
        uses: lhy0403/install-qt-action@v2
        with:
          modules: qtcharts
# --------------------------------------------------------
      - name: Install Packages 
        run: |
          sudo add-apt-repository ppa:webispy/grpc
          sudo add-apt-repository ppa:carsten-uppenbrink-net/openssl
          sudo apt update
          sudo apt install -y libgl-dev openssl libx11-dev libxkbcommon-x11-dev libgrpc++-dev libprotobuf-dev protobuf-compiler protobuf-c-compiler protobuf-compiler-grpc
# --------------------------------------------------------
#      - name: Extracting gRPC and protobuf libs and headers
#        run: tools/grpc_gen.sh
# --------------------------------------------------------
      - name: Download libqvb static library.
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: Qv2ray/QvRPCBridge
          tag: 'latest'
          path: libs
          file: libqvb-linux64.a
# --------------------------------------------------------
      - name: Building Qv2ray
        run: |
          mkdir build
          cd build
          qmake .. CONFIG+=no_increase_build_number CONFIG+=with_new_backend PREFIX=/usr
          make -j2
      - name: Generating filesystem structure for AppImage
        run: | 
          cd build
          make install INSTALL_ROOT=AppDir
          cd AppDir
          mkdir -p ./usr/lib/
          cp /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 ./usr/lib/
      - name: Building AppImage using linuxdeployqt
        run: |
          cd build
          wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
          chmod +x ./linuxdeployqt-6-x86_64.AppImage
          ./linuxdeployqt-6-x86_64.AppImage --appimage-extract 
          cd AppDir
          ../squashfs-root/AppRun usr/share/applications/qv2ray.desktop -appimage -no-strip -always-overwrite
          mv ./Qv2ray*.AppImage ./Qv2ray.AppImage
      - name: Uploading artifact
        uses: actions/upload-artifact@master
        with:
          name: Qv2ray.linux.AppImage
          path: build/AppDir/Qv2ray.AppImage
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/AppDir/Qv2ray.AppImage
          asset_name: Qv2ray-${{ github.ref }}-linux.AppImage
          tag: ${{ github.ref }}
          overwrite: true


